# Prediction Model

In [1]:
# importing librairies ...
import pandas as pd

In [ ]:
# The first step is to retrieve cleaned data 
df18 = pd.read_csv('./dataset/immoCollect18-clean.csv')
df52 = pd.read_csv('./dataset/immoCollect52-clean.csv')

In [ ]:
df18.head()

In [ ]:
df52.head()

In [5]:
df18.head()

,Unnamed: 0,Prix,Type de propriété,Bien neuf,Code Postal,Surface habitable,Nombre de chambre(s),Jardin,Terrasse
0,0,280000,0,True,1180,65,1,True,True
1,1,282500,0,True,1180,73,1,False,True
2,2,412500,0,True,1180,100,2,False,True
3,3,380000,0,True,1160,87,2,False,True
4,4,165000,0,True,6000,63,1,False,False

In [6]:
df52.head()

,Unnamed: 0,postal_code,type_of_property,price,number_of_rooms,house_area,fully_equipped_kitchen,terrace,garden,state_of_the_building,...,locality,province,region,head_city,CD_REFNIS,living_surface_ha,population,pop_per_km2,total_per_build_km2,ratio_free_build
0,5,1650,0,525000,4,220,1,1,1,0,...,Beersel,Brabant flamand (le),Région flamande,Hal-Vilvorde,23003.0,693.7091,25343.0,833.694047,0.000438,-2.851322
1,18,7850,0,550000,4,276,1,1,1,1,...,Enghien,Hainaut (le),Région wallonne,Ath,51067.0,423.2891,14061.0,356.848789,0.000931,-2.097867
2,19,4020,0,85000,2,110,1,0,0,0,...,Liège,Liège,Région wallonne,Liège,62063.0,1532.7558,197217.0,2876.075706,0.000447,-2.830605
3,21,1700,0,525000,4,260,1,1,1,0,...,Dilbeek,Brabant flamand (le),Région flamande,Hal-Vilvorde,23016.0,957.6382,43423.0,1046.977241,0.000433,-2.863048
4,22,4000,0,150000,4,247,1,1,0,0,...,Liège,Liège,Région wallonne,Liège,62063.0,1532.7558,197217.0,2876.075706,0.000447,-2.830605